image: "ubuntu:18.04"

before_script:
  - ci/install-dependencies.sh

variables:
  GIT_DEPTH: "2147483647"
  SLEEP_A_BIT: "sleep 0.2"
  VERBOSE: "1"

gcc-x86_64-libdw-valgrind:
  stage: test
  script: ci/run-build-and-tests.sh
  variables:
    CC: "gcc"
    TARGET: "x86_64"
    STACKTRACE: "libdw"
    CHECK: "valgrind"
    TIMEOUT_DURATION: "2400"
    VALGRIND_TOOLS: "memcheck"
    VALGRIND_TESTDIR: "tests"
    VALGRIND_TESTS: "looping_threads.test"
