image: "ubuntu:17.10"

before_script:
  - ci/install-dependencies.sh

variables:
  GIT_DEPTH: "2147483647"
  SLEEP_A_BIT: "sleep 0.2"
  VERBOSE: "1"

musl-x86_64:
  stage: test
  script: ci/run-build-and-tests.sh
  variables:
    CC: "musl-gcc"
    TARGET: "x86_64"
    KHEADERS: "torvalds/linux"

musl-x86:
  stage: test
  script: ci/run-build-and-tests.sh
  variables:
    CC: "musl-gcc"
    TARGET: "x86"
    KHEADERS: "torvalds/linux"
